export const CLEAR_POST = 'clear_post'
export const FETCH_POST_ACTIVE_SUCCESS = 'fetch_post_active_success'
export const FETCH_POST_SUCCESS = 'fetch_post_success'
export const FETCH_POST_ERROR = 'fetch_post_error'
export const SEND_LIKES_DATA = 'send_likes_data'
export const SAVE_POST_SUCCESS = 'save_post_success'
export const SAVE_POST_ERROR = 'save_post_error'
export const UPDATE_POST_SUCCESS = 'update_post_success'
export const DELETE_POST_SUCCESS = 'delete_post_success'
export const DELETE_POST_ERROR = 'delete_post_error'

export const GET_UPDATE_INDEX_SUCCESS = 'get_update_index_success'
export const GET_UPDATE_TABLE_SUCCESS = 'get_update_table_success'